- hosts: 127.0.0.1
  tasks:
    - name: Generate kubeconfig for each worker node
      shell: |
        KUBERNETES_PUBLIC_ADDRESS=$(cat /tmp/lb_ip)
        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://${KUBERNETES_PUBLIC_ADDRESS}:6443 \
        --kubeconfig=worker-{{i}}.kubeconfig
        kubectl config set-credentials system:node:worker-{{i}} \
        --client-certificate=worker-{{i}}.pem \
        --client-key=worker-{{i}}-key.pem \
        --embed-certs=true \
        --kubeconfig=worker-{{i}}.kubeconfig
        kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:node:worker-{{i}} \
        --kubeconfig=worker-{{i}}.kubeconfig
        kubectl config use-context default --kubeconfig=worker-{{i}}.kubeconfig
      loop: "{{ range (0, 2) }}"
      loop_control:
        index_var: i

    - name: Generate kube-proxy
      shell: |
        KUBERNETES_PUBLIC_ADDRESS=$(cat /tmp/lb_ip)
        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://${KUBERNETES_PUBLIC_ADDRESS}:6443 \
        --kubeconfig=kube-proxy.kubeconfig
        kubectl config set-credentials system:kube-proxy \
          --client-certificate=kube-proxy.pem \
          --client-key=kube-proxy-key.pem \
          --embed-certs=true \
          --kubeconfig=kube-proxy.kubeconfig
        kubectl config set-context default \
          --cluster=kubernetes-the-hard-way \
          --user=system:kube-proxy \
          --kubeconfig=kube-proxy.kubeconfig
        kubectl config use-context default --kubeconfig=kube-proxy.kubeconfig

    - name: Generate kube-controller-manager
      shell: |
        KUBERNETES_PUBLIC_ADDRESS=$(cat /tmp/lb_ip)
        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=kube-controller-manager.kubeconfig
        kubectl config set-credentials system:kube-controller-manager \
          --client-certificate=kube-controller-manager.pem \
          --client-key=kube-controller-manager-key.pem \
          --embed-certs=true \
          --kubeconfig=kube-controller-manager.kubeconfig
        kubectl config set-context default \
          --cluster=kubernetes-the-hard-way \
          --user=system:kube-controller-manager \
          --kubeconfig=kube-controller-manager.kubeconfig
        kubectl config use-context default --kubeconfig=kube-controller-manager.kubeconfig

    - name: Generate kube-scheduler
      shell: |
        KUBERNETES_PUBLIC_ADDRESS=$(cat /tmp/lb_ip)
        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=kube-scheduler.kubeconfig
        kubectl config set-credentials system:kube-scheduler \
          --client-certificate=kube-scheduler.pem \
          --client-key=kube-scheduler-key.pem \
          --embed-certs=true \
          --kubeconfig=kube-scheduler.kubeconfig
        kubectl config set-context default \
          --cluster=kubernetes-the-hard-way \
          --user=system:kube-scheduler \
          --kubeconfig=kube-scheduler.kubeconfig
        kubectl config use-context default --kubeconfig=kube-scheduler.kubeconfig

    - name: Generate admin
      shell: |
        KUBERNETES_PUBLIC_ADDRESS=$(cat /tmp/lb_ip)
        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=admin.kubeconfig
        kubectl config set-credentials admin \
          --client-certificate=admin.pem \
          --client-key=admin-key.pem \
          --embed-certs=true \
          --kubeconfig=admin.kubeconfig
        kubectl config set-context default \
          --cluster=kubernetes-the-hard-way \
          --user=admin \
          --kubeconfig=admin.kubeconfig
        kubectl config use-context default --kubeconfig=admin.kubeconfig

- hosts: worker_0
  tasks:
    - name: kube stuff to worker 0
      copy:
        src: "{{ item }}"
        dest: "."
      with_items:
        - worker-0.kubeconfig
        - kube-proxy.kubeconfig 
      

- hosts: worker_1
  tasks:
    - name: kube stuff to worker 1
      copy:
        src: "{{ item }}"
        dest: "."
      with_items:
        - worker-1.kubeconfig
        - kube-proxy.kubeconfig   
      

- hosts: controllers
  tasks:
    - name: Copy kube stuff to controllers
      copy:
        src: "{{ item }}"
        dest: "."
      with_items:
        - admin.kubeconfig
        - kube-controller-manager.kubeconfig 
        - kube-scheduler.kubeconfig     