- hosts: controllers
  tasks:  
    - name: download etcd binaries
      get_url:
        url: "{{ item }}"
        dest: /tmp
      with_items:
        - https://github.com/etcd-io/etcd/releases/download/v3.3.20/etcd-v3.3.20-linux-amd64.tar.gz

    - name: untar
      shell: |
        tar -xvf /tmp/etcd-v3.3.20-linux-amd64.tar.gz

    - name: move etcd
      shell: |
        sudo mv etcd-v3.3.20-linux-amd64/etcd* /usr/local/bin/
        sudo mkdir -p /etc/etcd /var/lib/etcd
        sudo cp ca.pem kubernetes-key.pem kubernetes.pem /etc/etcd/

    - name: configure etcd server
      shell: |
        INTERNAL_IP=$(ip addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
        ETCD_NAME=$(hostname -s)

        cat > etcd.service <<EOF
        [Unit]
        Description=etcd
        Documentation=https://github.com/coreos

        [Service]
        Type=notify
        ExecStart=/usr/local/bin/etcd \\
          --name ${ETCD_NAME} \\
          --cert-file=/etc/etcd/kubernetes.pem \\
          --key-file=/etc/etcd/kubernetes-key.pem \\
          --peer-cert-file=/etc/etcd/kubernetes.pem \\
          --peer-key-file=/etc/etcd/kubernetes-key.pem \\
          --trusted-ca-file=/etc/etcd/ca.pem \\
          --peer-trusted-ca-file=/etc/etcd/ca.pem \\
          --peer-client-cert-auth \\
          --client-cert-auth \\
          --initial-advertise-peer-urls https://${INTERNAL_IP}:2380 \\
          --listen-peer-urls https://${INTERNAL_IP}:2380 \\
          --listen-client-urls https://${INTERNAL_IP}:2379,https://127.0.0.1:2379 \\
          --advertise-client-urls https://${INTERNAL_IP}:2379 \\
          --initial-cluster-token etcd-cluster-0 \\
          --initial-cluster controller-0=https://10.240.0.10:2380,controller-1=https://10.240.0.11:2380,controller-2=https://10.240.0.12:2380 \\
          --initial-cluster-state new \\
          --data-dir=/var/lib/etcd
        Restart=on-failure
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
        EOF
    
    - pause:
        seconds: 5

    - name: move newly created file
      shell: |
        sudo mv etcd.service /etc/systemd/system/

    - name: starting server
      shell: |
        sudo systemctl daemon-reload
        sudo systemctl enable etcd
        sudo systemctl start etcd