- hosts: workers
  tasks:
    - name: updating packages
      shell: |
        sudo apt-get update
        sudo apt-get -y install socat conntrack ipset
    
    - name: downloading binaries
      get_url:
        url: "{{ item }}"
        dest: "."
      with_items:
        - https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.17.0/crictl-v1.17.0-linux-amd64.tar.gz 
        - https://storage.googleapis.com/gvisor/releases/nightly/latest/runsc 
        - https://github.com/opencontainers/runc/releases/download/v1.0.0-rc10/runc.amd64
        - https://github.com/containernetworking/plugins/releases/download/v0.8.5/cni-plugins-linux-amd64-v0.8.5.tgz 
        - https://github.com/containerd/containerd/releases/download/v1.3.2/containerd-1.3.2.linux-amd64.tar.gz 
        - https://storage.googleapis.com/kubernetes-release/release/v1.17.3/bin/linux/amd64/kubectl 
        - https://storage.googleapis.com/kubernetes-release/release/v1.17.3/bin/linux/amd64/kube-proxy 
        - https://storage.googleapis.com/kubernetes-release/release/v1.17.3/bin/linux/amd64/kubelet
    
    - name: make directories
      shell: |
        sudo mkdir -p \
        /etc/cni/net.d \
        /opt/cni/bin \
        /var/lib/kubelet \
        /var/lib/kube-proxy \
        /var/lib/kubernetes \
        /var/run/kubernetes
    
    - name: install worker binaries
      shell: |
        sudo mv runc.amd64 runc
        chmod +x kubectl kube-proxy kubelet runc runsc
        sudo mv kubectl kube-proxy kubelet runc runsc /usr/local/bin/
        sudo tar -xvf crictl-v1.17.0-linux-amd64.tar.gz -C /usr/local/bin/
        sudo tar -xvf cni-plugins-linux-amd64-v0.8.5.tgz -C /opt/cni/bin/
        sudo tar -xvf containerd-1.3.2.linux-amd64.tar.gz -C /