kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 4jAetYo3fUQetYBgwBM3jpeU2KZj3BMYxp4gcvquDu8=
      - identity: {}
